name: Dependency Scan

on:
  workflow_call:

jobs:
  dependency-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Backend dependency scan
        run: |
          cd backend
          npm install
          npm audit --audit-level=high
