name: Deploy to EC2

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## Connects GitHub runner to EC2 server via SSH
      - name: Deployy via SSH 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}      ## EC2 public ip
          username: ${{ secrets.EC2_USER }}  ## SSH username 
          key: ${{ secrets.EC2_KEY }}        ## private SSH key
          script: |
          
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            docker network create delish-net || true

            docker pull ${{ secrets.DOCKER_USERNAME }}/delish-project-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/delish-project-frontend:latest

            docker stop nginx || true
            docker stop backend || true
            docker stop frontend || true

            docker rm nginx || true
            docker rm backend || true
            docker rm frontend || true

            docker run -d \
              --name backend \
              --network delish-net \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/delish-project-backend:latest

            docker run -d \
              --name frontend \
              --network delish-net \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/delish-project-frontend:latest

           
 