name: End-to-End DevSecOps pipeline
on:
  push:
    branches:
      - main
jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

  docker-linting:
    needs: [code-quality, secret-scan, dependency-scan]
    uses: ./.github/workflows/docker-linting.yml

  build-and-push:
    needs: [docker-linting]
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit

  image-scan:
    needs: [build-and-push]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

  deploy:
    needs: [image-scan]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
