name: End-to-End DevSecOps pipeline

on:
  push:
    branches:
      - main

jobs:
  code-deps-checks:
    uses: ./.github/workflows/code-deps-checks.yml

  secret-scan:
    uses: ./.github/workflows/secret-scan.yml

  docker-linting:
    needs: [code-deps-checks, secret-scan]
    uses: ./.github/workflows/docker-linting.yml

  build-scan-push:
    needs: [docker-linting]
    uses: ./.github/workflows/build-scan-push.yml
    secrets: inherit

  deploy:
    needs: [build-scan-push]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
