name: Docker Lint

on:
  workflow_call:

jobs:
  Docker-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint frontend Dockerfile
        run: docker run --rm -i hadolint/hadolint < frontend/Dockerfile

      - name: Lint backend Dockerfile
        run: docker run --rm -i hadolint/hadolint < backend/Dockerfile
