name: Container Scan

on:
  workflow_call:

jobs:
  Image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan frontend image
        run: docker run --rm aquasec/trivy:0.50.1 image ${{ secrets.DOCKER_USERNAME }}/delish-frontend

      - name: Scan backend image
        run: docker run --rm aquasec/trivy:0.50.1 image ${{ secrets.DOCKER_USERNAME }}/delish-backend
