name: Secret Scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
  
