name: Secret Scan

on:
  workflow_call:

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run TruffleHog
        run: |
          docker run --rm -v $PWD:/repo trufflesecurity/trufflehog:latest filesystem /repo
